### ISSUE TITLE
Exposed auth data

### ISSUE THREAD

**Issue by LossyDragon** [guilhermec-costa/SteamAnalyser#1]
Not sure how important the account youre using testing your app, but I see guardData.txt contains your session data. 

This should be considered sensitive information 😅

**Comment by guilhermec-costa** [comment]
Hey Lossy!
Thanks 😅

I'm using a test account, not my official. It is fine xD

I'm now persisting the token, so that the login process is not triggered
every time the application start.
But I will definitely put it in the .gitignore.

But thank you again for telling me!

**Comment by LossyDragon** [comment]
❤️
